version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - macvlan_network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.3
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      KIBANA_DEFAULT_APP_ID: "wazuh"
      SERVER_NAME: kibana.example.com
    ports:
      - 5601:5601
    networks:
    - macvlan_network

  wazuh:
    image: wazuh/wazuh
    container_name: wazuh
    ports:
      - 1514:1514/tcp
      - 1514:1514/udp
    volumes:
      - ./wazuh:/var/ossec/data
    environment:
      - WAZUH_MANAGER='yes'
    networks:
      - macvlan_network

  logstash:
    image: docker.elastic.co/logstash/logstash:7.9.3
    container_name: logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/config/logstash.conf:/usr/share/logstash/config/logstash.conf
    environment:
      - "XPACK_MONITORING_ENABLED=false"
      - "ES_HOSTS=http://elasticsearch:9200"
    networks:
      - macvlan_network

volumes:
  esdata:

networks:
  etworks:
  macvlan_network:
    driver: macvlan
    driver_opts:
      parent:  enp7s0
    ipam:
      driver: default
      config:
        - subnet: 172.21.202.0/24
          gateway: 172.21.202.254
          
          
          ----------------------------------------
          version: "3.7"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=<your-elasticsearch-password>
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=<path-to-ssl-key>
      - xpack.security.http.ssl.certificate=<path-to-ssl-certificate>
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.2
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=<your-elasticsearch-password>
      - xpack.security.enabled=true
    ports:
      - "5601:5601"

  logstash:
    image: docker.elastic.co/logstash/logstash:7.16.2
    volumes:
      - ./config/logstash/:/usr/share/logstash/pipeline/
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=<your-elasticsearch-password>

volumes:
  elasticsearch-data:
