version: '3.6'
services:

  Elasticsearch:
    image: elasticsearch:7.16.2
    container_name: elasticsearch
    restart: always
    volumes:
    - elastic_data:/usr/share/elasticsearch/data/
    environment:
    - "ES_JAVA_OPTS=-Xmx1g -Xms1g"
    - "discovery.type=single-node"
    - xpack.security.enabled=true
    - xpack.security.authc.api_key.enabled=true
    - ELASTIC_PASSWORD=elastic

    ports:
    - "9200:9200"
    - "9300:9300"
    networks:
      - macvlan_network1

  Logstash:
    image: logstash:7.16.2
    container_name: logstash
    restart: always
    volumes:
    - ./logstash/:/logstash_dir
    command: logstash -f /logstash_dir/logstash.conf
    depends_on:
      - Elasticsearch
    ports:
      - "9600:9600"
    environment:
      - "LS_JAVA_OPTS=-Xmx256m -Xms256m"
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=elastic
      - xpack.security.enabled=true
      - xpack.monitoring.elasticsearch.hosts=http://elasticsearch:9200
      - xpack.monitoring.elasticsearch.username=elastic
      - xpack.monitoring.elasticsearch.password=elastic
    networks:
      - macvlan_network1
  Kibana:
    image: kibana:7.16.2
    container_name: kibana
    restart: always
    ports:
    - "5601:5601"
    environment:
      - "LS_JAVA_OPTS=-Xmx256m -Xms256m"
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=elastic
      - xpack.security.enabled=true
    depends_on:
      - Elasticsearch
    networks:
      - macvlan_network1

volumes:
  elastic_data: {}

networks:
  macvlan_network1:
    driver: macvlan
    driver_opts:
      parent: enp7s0
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/24
          gateway: 172.19.0.254
